baystation12.dme
code/game/jobs/job_controller.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/religion/_defines.dm
code/modules/religion/old gods/greed.dm
code/modules/religion/old gods/messiah.dm
code/modules/religion/old gods/old_god_shrines.dm
code/modules/religion/old gods/old_god_spells.dm
maps/frontier/frontier_areas.dm

Why did I bother making a fork

A whole lot of fixes, and some new shit.

---

code/__defines/subsystems.dm
code/_helpers/global_access.dm
code/datums/datum.dm
code/datums/extensions/extensions.dm
code/datums/observation/destroyed.dm
code/datums/observation/moved.dm
code/datums/weakref.dm
code/game/atoms_movable.dm
code/game/world.dm
code/modules/lighting/lighting_atom.dm
code/modules/lighting/lighting_turf.dm
code/modules/mob/observer/freelook/update_triggers.dm
code/unit_tests/unit_test.dm

Not actually Z-Mimic but small changes.

Confusing branch name

---

code/datums/mind.dm

Should add psionics to the player panel

---

code/_onclick/hud/screen_objects_alt.dm

unfucks screen objects

---

code/_onclick/other_mobs.dm

unfucks other mobs

---

code/modules/mob/mob.dm
code/modules/psionics/faculties/redaction.dm

UNLIMITED POWER (psionic further fixes)

---

code/_onclick/other_mobs.dm
code/controllers/subsystems/psi.dm
code/datums/mind.dm
code/modules/admin/admin.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/living_defense.dm
code/modules/psionics/complexus/complexus.dm
code/modules/psionics/complexus/complexus_helpers.dm
code/modules/psionics/complexus/complexus_process.dm
code/modules/psionics/equipment/psipower_tinker.dm
code/modules/psionics/faculties/psychokinesis.dm
code/modules/psionics/mob/mob_interactions.dm

psionics was ported via downgrading all the code, we are upgrading to the newest code and fixing shit along the way

READY TO MERGE | Psionics code re-overhaul and unfucking

---

code/game/objects/items/weapons/melee/energy.dm

goes from being "may the force be with you" to "An elegant weapon, for a more civilized age."

CHANGES e-sword description

---

code/modules/library/lib_items.dm

adds a way to powergay your intelligence up at a decent rate.

Intelligence is Key

---

code/modules/mob/stats_skills.dm

unfucks skills (untested)

---

code/game/objects/items/weapons/material/swords.dm
code/game/objects/items/weapons/stunbaton.dm
code/game/objects/items/weapons/swords_axes_etc.dm
code/game/objects/items/weapons/tools.dm
code/modules/mob/living/carbon/human/human_attackhand.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/matt_combat.dm

Also makes dodging easier across the board.
Fucked detached head state

Makes parrying easier, and ads it for ALL batons + crowbars

---

code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/matt_combat.dm
code/modules/mob/living/carbon/human/vision_cone.dm

Begins to nerf dismembers towards limbs and head, instead of just using a statcheck. This was dumb.

Beginning of dismember nerfs (THIS WAS RETARDED)

---

code/game/objects/effects/decals/Cleanable/bloodpool.dm
code/modules/mob/living/carbon/human/life.dm

You can clean them, if you walk through them you leave trails of different lengths depending on the size of the blood pool, if you get up or leave the turf or whatever while in a growing blood pool it will cease it's growth, i don't think it has DNA, I'm not really sure honestly, but the blood under the actual pool decal has DNA if you are into that sort of stuff. 
It triggers if you ale laying down while bleeding from your organs, and while you have blood, please change the check if you have a better more reliable one, as this is wack. If you stab yourself with a scalpel and other sharp things, it wont work bc maybe it does't deal organ damage, if you get cut from a saw or shot or the likes, it will trigger.
That's most of it, not sure about efficiency.

Blood pools

---

code/game/gamemodes/gameticker.dm

Changed "Hell is let loose." color (light pink)

---

README.md

:cl: Turret
tweak: Yell at me in-game!
/:cl:

Test, number two.

---

code/modules/research/designs.dm

pidoras count stole my boombox
if it's too easy to access i can just increase the science requirements

adds boombox to science after you research some shit

---

code/datums/uplink/highly_visible_and_dangerous_weapons.dm
code/datums/uplink/stealthy_and_inconspicuous_weapons.dm
code/game/objects/items/devices/PDA/cart.dm
code/game/objects/items/devices/hacktool.dm
code/game/objects/items/devices/radio/encryptionkey.dm
code/game/objects/items/devices/radio/radio.dm
code/game/objects/items/devices/suit_sensor_jammer.dm
code/game/objects/items/toys.dm
code/game/objects/items/weapons/cards_ids.dm
code/game/objects/items/weapons/circuitboards/computer/computer.dm
code/game/objects/items/weapons/explosives.dm
code/game/objects/items/weapons/grenades/anti_photon_grenade.dm
code/game/objects/items/weapons/grenades/explosive.dm
code/game/objects/items/weapons/grenades/supermatter.dm
code/game/objects/items/weapons/implants/implants/explosive.dm
code/game/objects/items/weapons/implants/implants/freedom.dm
code/game/objects/items/weapons/implants/implants/uplink.dm
code/game/objects/items/weapons/storage/toolbox.dm
code/game/objects/items/weapons/storage/uplink_kits.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/armor.dm
code/modules/projectiles/ammunition/bullets.dm
code/modules/projectiles/guns/projectile/revolver.dm

gave syndie holdout pistol, revolver and fuckvolver(no ammo)
made most syndie items have a tech value
made most ammo have a tech value

Traitor shit

---

code/modules/mob/living/carbon/human/combat.dm
code/modules/mob/living/carbon/human/examine.dm

Fixes rest delay and human examining

---

code/datums/outfits/jobs/science.dm
code/game/objects/items/weapons/cards_ids.dm
code/modules/GURPS/stats_skills.dm
maps/shared/job/jobs.dm

also makes ids fit on the face. I might actually remove this later on, i need to test something first.

Changes how stats are assigned to be weighted random

---

code/game/machinery/cryopod.dm

i couldn't find why this was happening, someone else look into it

fixes the fact that cryo pods spam you by removing the message itself

---

code/modules/mob/living/carbon/human/human.dm

turret you fucking retard why did you just paste the code
do we have var/obj/item/weapon/gun/projectile/heavysniper/S in the code you retard

Adds zooming in but without turret's retard code
